---

- name: Ensure that server is started
  service: name=postgresql.service state=started
  tags: services

- name: Create users
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ item.name }} 
                   role_attr_flags={{ item.role|default() }} 
  with_items: postgresql.users
