---

- name: Add repository key
  apt_key: data="{{ lookup('file', 'ACCC4CF8.asc') }}"

- name: Add PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'

# Needed for apt_repository and postgresql_user
- name: Installing Ansible deps
  apt: pkg={{ item }}
  with_items:
    - python-software-properties
    - libpq-dev
    - python-psycopg2
